### PR TITLE
Fix typos and links in example notebooks and userguide/geometry

### PR DESCRIPTION
**Pull request by johnnyliu27**
This PR continues to fix the typos and expired links I found in example notebooks of basic usage when I read them.

One special thing to note: in _**In [29]**_ of the [Pandas Dataframs](http://openmc.readthedocs.io/en/latest/examples/pandas-dataframes.html) notebook, the variable _data_ was intended to contain 10 values, but in the output there is only 1 value printed. I found the problem is in the argument `filter_bins`:

`filter_bins=[(i,) for i in range(10)]`

Instead using the following line will make it work as expected:

`filter_bins=[tuple(i for i in range(10))]`

But it's a forced type change, so I think there might be a better way of fixing it but I didn't find it.

### CODE REVIEW

**Comment by paulromano** [comment]
Thanks again for more fixes, @johnnyliu27. I think you're right about the filter_bins argument, although `filter_bins=[tuple(range(10))]` should also work and would be more compact. You can go ahead and change that too.

**Comment by johnnyliu27** [comment]
Thanks! But it's weird that I didn't get the same tally data as in the example notebook, although the keff was exactly the same for every batch. (I'm using version 0.9.0.) Any idea on this?

**Comment by paulromano** [comment]
Not sure exactly why that's happening but I'm seeing the same thing. In fact, even when I go back to the commit that the notebook was originally run with and re-run it, I still get different answers, but the answers I get are consistent with those that I get running it with the most recent commit. So, I wouldn't worry about it.

**Comment by johnnyliu27** [comment]
Thanks! @paulromano  Just updated the tally data by re-run the notebook after fixing input 29.

**Pull request merged**
