### PR TITLE
Thermal scattering fixes and improvements

### PR DESCRIPTION
**Pull request by paulromano**
This pull request makes a number of bug fixes and improvements relating to how S(a,b) data is treated. The changes are as follows:

- Expand the list of recognized thermal scattering evaluations to match what will be available in ENDF/B-VIII.0
- Fix a bug when converting incoherent elastic data from ACE files. The number of mu bins was one too few. Interestingly, it appears the NNDC S(a,b) data files were processed incorrectly (no incoherent elastic data appears even for materials that should have it) so the bug fix doesn't change any results. I've confirmed that the distributions look correct now for MCNP 6.1 data (which was processed correctly). The following materials should have incoherent elastic data: H in CH4 (solid), H in CH2, H in ZrH, Zr in ZrH.
- The way that the list of applicable nuclides on an S(a,b) table is assigned has been changed. Before, we relied on whatever was in the ACE file. Now when an isotope is encountered, e.g. C12, all naturally-occurring isotopes are added as well as the natural-element version which in this example would be C0, C12, and C13 (Note that this is not done for H or Fe56).
- A bug in the NNDC library with Be in BeO and O in BeO has been fixed. On the Be in BeO table, O16 is incorrectly listed as an applicable nuclide, and on O in BeO, Be9 is incorrectly listed. This caused the test result for test_salphabeta to change (since the model includes BeO).
- OpenMC was not correctly applying S(a,b) tables to multiple isotopes when it was supposed to. This has been fixed.
- The algorithm for sampling angles from a continuous S(a,b) table has been changed to match MCNP's treatment (the angle is smeared over a range of mu values based on how close the neighboring mu values are). This change will be familiar to @cchaugen.

### CODE REVIEW

**Comment by liangjg** [comment]
@paulromano the update on assigning S(a,b) to multiple isotopes looks great!  I'm closing #775 and #676 once this PR is merged. But, as the length of `mat % i_sab_tables(:)` may be not equal to `mat % n_sab`, the former should be used when calculating xs?

[line 82-83 in cross_section.F90](https://github.com/paulromano/openmc/blob/c407dc025947b1d0fcdf5eca5971766eb71ecd59/src/cross_section.F90#L82-L83)

``` fortran
            ! Don't check for S(a,b) tables if there are no more left
            if (j > mat % n_sab) check_sab = .false.
```

should be 

``` fortran
            ! Don't check for S(a,b) tables if there are no more left
            if (j > size(mat % i_sab_tables)) check_sab = .false.
```
?

**Comment by paulromano** [comment]
@liangjg Nice catch! I'll fix that momentarily.

**Comment by wbinventor** [comment]
I perused this PR and it looks fine to me. Perhaps @liangjg, @cchaugen or @samuelshaner should review and merge (once the test suite passes) though since they are more familiar with S(a,b) logic than me.

**Comment by liangjg** [comment]
I have no more comments. Good to go for me. @wbinventor

**Comment by paulromano** [comment]
@liangjg @wbinventor Test suite passes now -- just needed to clear out the cache on Travis since I updated the data.

**Pull request merged**
