### PR TITLE
Ensure mutable objects are not hashable

### PR DESCRIPTION
**Pull request by paulromano**
As discussed in #872, we are violating a basic contract in Python regarding equality and hashing for many of our classes. The problem is summarized in Python's documentation of `__hash__`:

> If a class defines mutable objects and implements an `__eq__()` method, it should not implement `__hash__()`, since the implementation of hashable collections requires that a key’s hash value is immutable (if the object’s hash value changes, it will be in the wrong hash bucket).

As a demonstration of this:

```Python
>>> c = openmc.Cell()
>>> s = {c}
>>> c.id = 10
>>> c in s
False
```

So, the proper solution to this is to either make our types immutable or to get rid of the `__hash__` methods. A second question is whether we should get rid of the `__eq__` methods too. In this pull request, I am proposing that we mostly get rid of `__eq__` for the following reason: by default, when you override `__eq__`, the type becomes unhashable and thus you can't use it in a set or as a dictionary key. I do find it useful to have sets and dictionaries of our types; in fact, we use this in our `Plot` class right now:

```Python
p = openmc.Plot()
p.colors = {fuel: 'yellow', water: 'blue'}
```
where `fuel` and `water` are instances of `Cell` (or `Material`).

For most classes, removing `__hash__` and `__eq__` doesn't cause any problems. There are a few cases where we have to be careful though. In some cases, we have been relying on the fact that two mutable objects that are different can actually compare equal and hash to the same value. Namely, filters are cloned often in the openmc.mgxs module and this results in filters that are the same but with different IDs, which currently hash to the same value. If we removed that, then each of the copies of the filters will get written to XML separately and will require a separate search at runtime. So, filters are going to require a little more work; I actually haven't touched them in this PR.

The same thing sort of happens with meshes (we check at XML-writing time to make sure the same mesh doesn't get written twice), but in this case, we really are just trying to avoid multiple references to the same mesh resulting in it getting written multiple times. I made a small change so that we just check mesh IDs when writing XML so that the same mesh isn't written twice.

The only classes that I've substantially changed are `Nuclide`, `Element`, and `Macroscopic`, which I've changed into immutable subclasses of `str`. There's no good reason for these to be mutable and in fact they are really not providing much for us over a normal string. The only extra attribute we were using is the iso-in-lab stuff for nuclides; I've changed this to be an attribute of a material instead (I've also made a memory optimization on the Fortran side where the `material % p0` array is not allocated unless it's actually being used). Eventually, we should just be able to get rid of these three classes altogether.

One related change I made in `Material` is to have `add_element` immediately add individual isotopes rather than deferring this to XML-writing time. This was done for performance reasons (namely, if a material with elements is cloned, then each of the clones will have to have their elements expanded at XML writing time). This simplifies the internal representation of materials and makes it more-or-less match the Fortran side.

### CODE REVIEW

**Comment by smharper** [comment]
Always good to see a PR with net negative LoC!

One small request: inside of `Tally.merge` there is a `if self == other` that should always evaluate to `False`.  Just remove that `if` block.  It looks like the function will still work fine without it.

I'm happy to merge after that one small change, but you're willing to it would also be nice to get rid of the `Filter.__eq__` and `Filter.__hash__` methods.  It's always better to remove stuff like this early just in case users start relying on them.  I think that we can practically replace `Filter.__eq__` with `Filter.can_merge`.  The tally merging logic sometimes uses `__eq__` to prevent unnecessary work, but I think it will still work fine even when `__eq__` evaluates to `False` for filters that are just copies of each other.

**Comment by paulromano** [comment]
OK -- I'll take a stab at the Filter classes. You're right that it's probably good to just fix it once and for all.

**Comment by paulromano** [comment]
So the filters are definitely a bit of a mess. Unlike the other classes where it clearly made sense to either have them be immutable (nuclides and elements) or mutable (cells, materials, etc.), we could go either way with filters. I originally thought that it would be easiest to just keep them as mutable and get rid of the rich comparison methods, but there's a ton of code in tallies.py that relies on the ability to use rich comparison methods on filters (e.g., `Tally._align_tally_data`, `Tally._swap_filters`, `Tally.filters.setter`, `Tally._can_merge_filters`, and `Tally.can_merge`) and we'd have to heavily refactor it if those methods were gone. So now I'm thinking the path of least resistance is to just have filters be immutable and allow them to keep the rich comparison methods. There are also problems with this approach:

- The `stride` `@property` of a filter wasn't really an intrinsic property of a filter. I've removed it and instead created a `strides` property of `Tally` (with the added benefit that we don't need to call `_update_filter_strides`) which makes a lot more sense.
- I was trying to create "cached" instances, i.e., if you instantiate a filter with the same arguments, you'd actually get back the same instance. However, I'm discovering that this is not going to work because `num_bins` could depend on the context of the filter -- for a mesh filter, the number of bins depends on whether it's being used in a volume tally or a surface current tally. Thus, we may need to have two separate instances of `MeshFilter` with the same bins but a different number of bins.

After thinking about it, the proper solution is actually to create a new `MeshSurfaceFilter` which is used specifically for CMFD. This would remove all the messiness of mesh and surface filters both on the Python and Fortran side. `MeshFilter` would specifically be for tallying volumetric quantities in each mesh cell and `SurfaceFilter` would specifically be for surface-crossing tallies. I'm hesitant to do that as part of this PR though since it will require substantial refactoring, so I'd prefer to hold off on that aspect and submit a separate PR later implementing `MeshSurfaceFilter`. I'll go ahead and commit some of the improvements I've already made and then leave it at that.

**Comment by smharper** [comment]
Agreed, filters get messy really quickly on both the Python or Fortran sides.  I want to believe there is a better abstraction, but they simply have to fill too many roles.  That said, I agree whole-heartedly that splitting the `MeshFilter` would be an improvement.

I'm happy with the state of this PR and I'll merge now.  FYI though, I would be hesitant to make filters immutable in a future PR.  I've started hearing complaints from more people than just @bforget about how fast our inputs are changing and this would be a major break in backwards-compatibility!

**Comment by paulromano** [comment]
Yeah, I hear you. It would be nice to get to a real version 1.0 where things could be considered a little more stable, but I personally don't feel we're there yet (namely, expansion of the C API and a C++ rewrite of core code has the potential to change interfaces).

**Pull request merged**
