### PR TITLE
Allow link-time-optimization with GCC

### PR DESCRIPTION
**Pull request by smharper**
This PR adds link-time-optimization flags when OpenMC is built with `-Doptimize=on`.  This allows GCC to optimize functions that are being called in different source files that they are defined in.  There is a noticeable increase in link time, but it's probably no more than a minute.  Our active neutron/s goes up by 5% with the "examples/pincell" inputs.

### CODE REVIEW

**Comment by paulromano** [comment]
@smharper Did you try it for any bigger problems, and if so what was the impact there? At one point in time, I did play around with interprocedural optimization with the Intel compiler (-ipo) and never found much benefit. Would be interesting if this 5% gain is consistent with gcc. I'll do some runs myself as well.

**Comment by smharper** [comment]
I get a 10% performance boost on a pincell problem with 32 million neutrons and a pretty heavy set of tallies.

(FWIW: When I really need speed I also copy `binary_search_real` into "cross_section.F90" and replace all occurrences `binary_search` with `binary_search_real`.  I haven't benchmarked that in awhile but I think that gave me an extra 5 to 10% depending on the problem.)

**Comment by paulromano** [comment]
Maybe we ought to inline binary search for cross section energy grid purposes then.

**Comment by smharper** [comment]
I hope that the compiler will inline it for us when the search is in the
same file

**Comment by paulromano** [comment]
With hope, one could also expect the compiler to inline it with LTO, no?

**Comment by smharper** [comment]
Good point. I suppose this discussion deserves empirical evidence

**Pull request merged**
