### PR TITLE
Simplify handling of energy in tally module

### PR DESCRIPTION
**Pull request by paulromano**
I realized when reviewing #893 that we could simplify how we choose energies in the tally module by just updating the `last_E` attribute of the particle at the top of the event loop in `tracking.F90`.

### CODE REVIEW

**Comment by paulromano** [comment]
Still need a reviewer for this small PR. @smharper? @nelsonag?

**Comment by smharper** [comment]
Whoops, this PR slipped my notice.  This code is much cleaner!  Merging.

**Comment by paulromano** [comment]
Thanks @smharper!

**Comment by nelsonag** [comment]
@paulromano @smharper Wait! I was just reviewing this.  Two things:
1. Should the p % coord index be 1 or p % n_coord.  Looks like the original source was inconsistent and at this time I can't remember why.
2. collision_mg needs to be updated in the same manner that collision(_ce) was.

**Comment by paulromano** [comment]
`p % coord` index should definitely be 1 -- the first set of coordinates refers to the coordinates relative to the root universe (i.e., the physical coordinates), which is what we want for these `last` attributes. The extra lines in collision_mg are not doing any harm but are superfluous at this point -- do you want to submit a hotfix PR removing those?

**Comment by smharper** [comment]
Sorry to cut you short @nelsonag!

**Pull request merged**
