### PR TITLE
Use a PPA to install HDF5 and PHDF5 on Travis

### PR DESCRIPTION
**Pull request by paulromano**
This PR changes our automated test runs on Travis CI to install HDF5 and PHDF5 from a PPA that backports a more recent version of HDF5 to Ubuntu 14.04. Importantly, HDF5 is compiled with `--enable-fortran2003` in that PPA. This should reduce ~10-15 mins of build-time (per configuration) for each new pull request.

### CODE REVIEW

**Comment by smharper** [comment]
How did you find this PPA?

**Comment by paulromano** [comment]
Google "ubuntu ppa hdf5", first result, scroll to bottom of page, click "Other versions of 'hdf5' in untrusted archives."

**Comment by smharper** [comment]
Can we modify the run_tests.py in some way that it will print out info confirming whether we are using a serial or parallel HDF5?

**Comment by paulromano** [comment]
When `cmake` is run, it shows what HDF5 libraries are linked, but the fact that we run `ctest` in script mode obscures this. I'm considering having Travis just run in normal mode (i,e., running `cmake`, `make`, `ctest`) which will give us all the normal output. I think it will also make it way easier to debug when errors occur. Just figuring out right now if there are any downsides to this (@bhermanmit??)

**Comment by smharper** [comment]
Script mode had something to do with CDash, right?  I don't even remember how to find our CDash now.

**Comment by paulromano** [comment]
Yeah, with script mode, you can run memory checks (via valgrind) or coverage runs (via gcov/lcov) and you can also submit results to a cdash. These are all things we don't do in our runs on Travis so I went ahead and flipped the switch. If you look at the current [run](https://travis-ci.org/mit-crpg/openmc/jobs/252539480), on line 1031 you'll see the HDF5 libraries (indicating that serial is being used for the hdf5-debug configuration).

**Comment by smharper** [comment]
Yes, this output is more helpful.  Thanks, @paulromano!

**Pull request merged**
