### PR TITLE
Fixed source leakage

### PR DESCRIPTION
**Pull request by walshjon**
This PR puts a fixed-source mode leakage calculation capability back into the code.  The same functionality used to be in there but was removed somewhere along the line.  Currently, the code does actually contain, and print out, a global leakage variable, but it is never accumulated to in fixed source mode, resulting in a reported leakage of ZERO.

### CODE REVIEW

**Comment by paulromano** [comment]
@walshjon Pretty sure this is my fault (#408). Thanks for catching! Would you mind submitting a PR that just fixes the behavior of the global leakage tally to be pulled to the release-0.7.0 branch? i.e. We'll keep this PR open to get the change to the display, but the actual bug fix with be a hotfix going to the release branch.

For this PR, I'd suggest cutting back on significant digits displayed. I'd say use 6 to stay in line with what's shown for k-effective and entropy. Otherwise, you get ugliness like the following:
```
     Batch            Mean Leakage              1sigma SEM
         1  1.0000000000000000E+00
         2  9.7999999999999998E-01  2.0000000000001673E-02
         3  9.6333333333333337E-01  2.0275875100993407E-02
         4  9.7250000000000003E-01  1.7017148213884857E-02
         5  9.7399999999999998E-01  1.3266499161421957E-02
         6  9.7666666666666668E-01  1.1155467020454059E-02
         7  9.7571428571428576E-01  9.4760708295859759E-03
         8  9.7875000000000001E-01  8.7500000000002263E-03
         9  9.7999999999999998E-01  7.8173595997064697E-03
        10  9.8199999999999998E-01  7.2724747430907202E-03
 Creating state point statepoint.10.binary...
```

Also, you should make a change to include leakage on test results so that we can catch bugs like this one I introduced in the future.

**Comment by walshjon** [comment]
The hotfix for the bug addressed in this slightly larger PR is now in #442.

You're not a fan of my ``ES24.16`` output format, @paulromano?!  Is it objectionable on purely aesthetic grounds?  I find it's sometimes useful in doing quick uncertainty propagation calcs, when you may only get 1 or 2 sig figs out of the 5 decimal places in the default output for the SEM value.

**Comment by wbinventor** [comment]
Do we not output the full floating point value in the statepoint file?

**Comment by paulromano** [comment]
Objectionable on aesthetic grounds and because you start to see effects from machine precision. I'm not opposed to using scientific notation, just with way too many digits.

@wbinventor I was just going to say -- if you're doing uncertainty propagation, you should be using the Python API!

**Comment by walshjon** [comment]
We do, but sometimes one could just want to run two quick calcs at the terminal to get differences in k or leakage.  Not a huge deal, though.

**Comment by wbinventor** [comment]
Asthetics is worth something @walshjon! Have fun learning Python (or hire a UROP if you feel too old for that stuff).

**Pull request merged**
