### PR TITLE
Use delayed fission bank to reduce generation-to-generation correlations

### PR DESCRIPTION
**Pull request by mjlong**
- The  new algorithm inserts an intermediate stage (containing n_delay batches) between inactive and active batches. 

- The fission_bank and master_fission_bank are enlarged by a factor of n_delay. 
Two new pointers bank_push_pointer and bank_pull_pointer are used to store neutrons into and obtain neutrons from different parts of the fission_bank.  

- During inactive batches, operations are performed on the first 1/n_delayed fraction of the fission_bank. 

- During intermediate batches, each of the n_delay batches writes to 1/n_delayed fraction of the fission_bank.

- During active batches, each batch gets neutron sources stored into the fission bank n_delay batches ago  and stores fission sites into the fission_bank for use after n_delay batches. 

- Multiple generations within one batch is allowed. 
Neutron source is delayed by n_delay batches. The generation_per_batch generations in one batch are treated as before. The last generation of each batch will obtain source produced n_delay batches ago for the next batch.

### CODE REVIEW

**Comment by siegela67** [comment]
Is there any analysis of or (numerical) experimental results with this approach?

**Comment by mjlong** [comment]
I submitted a summary for the coming ANS student conference. 

The figures below show the ACC and convergence rate comparison with traditional method. 

[ACC_compare.pdf](https://github.com/mit-crpg/openmc/files/138968/ACC_compare.pdf)
[RMS_compare.pdf](https://github.com/mit-crpg/openmc/files/138969/RMS_compare.pdf)

**Comment by smharper** [comment]
@mjlong, it looks like you based your changes on our "master" branch.  Please rebase it on the "develop" branch.

**Comment by paulromano** [comment]
@mjlong I think there needs to be more compelling evidence before we would consider merging this. While it makes sense that the correlation would be reduced during the active generations, there is a cost to having the intermediate stage. If you did the same run but without the intermediate stage (i.e. as we normally do), would your RMS really be better for the same total number of histories? My gut instinct is that it wouldn't be. To be clear, let's say you have two cases:

1. Skip M generations, use D generations to build up a delayed bank, and then run A active generations.
2. Skip M generations, run (D + A) active generations.

Is the RMS for case 1 better than case 2? And if so, can you explain why? It seems to me you'd get a benefit in the first D active generations (histories during that time are clearly less correlated with one another), but beyond that each history was started from a fission site created during a generation that was also active. Since we're interested in a reduction of absolute error, it shouldn't matter what order you simulate the histories in, and beyond the first D active generations, you've just effectively scrambled the order.

**Comment by wbinventor** [comment]
@paulromano mirrors my thoughts exactly. Seems like an effective figure of merit needs to be defined to effectively compare the two scenarios presented above on a level playing field.

**Comment by mjlong** [comment]
@paulromano @wbinventor 
- The figure below answers the question about comparing the "D delay + A active" and "D+A active" cases. The figure plots RMS over total (D+A) number of histories. 

[cost_compare_nhis.pdf](https://github.com/mit-crpg/openmc/files/139644/cost_compare_nhis.pdf)


- Taking into consideration the extra work between active generations due to the delayed fission bank, the figure below plots RMS over time cost. 

[cost_compare_time.pdf](https://github.com/mit-crpg/openmc/files/139645/cost_compare_time.pdf)

We will hold this PR until publish the analysis.

**Comment by paulromano** [comment]
Ok, closing this until things become a bit more mature.

**Pull request closed without merging**
