### PR TITLE
Add ASCII version of logo in output

### PR DESCRIPTION
**Pull request by paulromano**
This PR changes the `title` subroutine to display an ASCII version of our logo. The output will now look like:
```
                              %%%%%%%%%%%%%%%%%%
                         %%%%%%%%%%%%%%%%%%%%%%%%%%%%
                      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
              %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                                   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                                    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
           ###################       %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
          ######################       %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
          #######################       %%%%%%%%%%%%%%%%%%%%%%%%%%%%
          ########################       %%%%%%%%%%%%%%%%%%%%%%%%%%%%
          #########################       %%%%%%%%%%%%%%%%%%%%%%%%%%%
          ##########################       %%%%%%%%%%%%%%%%%%%%%%%%%%
          ############################      %%%%%%%%%%%%%%%%%%%%%%%%
          #############################      %%%%%%%%%%%%%%%%%%%%%%%
          ##############################       %%%%%%%%%%%%%%%%%%%%%
           #############################       %%%%%%%%%%%%%%%%%%%%
            ###########################       %%%%%%%%%%%%%%%%%%%%
             #########################      %%%%%%%%%%%%%%%%%%%%%
              ######################       %%%%%%%%%%%%%%%%%%%%%
               ####################       %%%%%%%%%%%%%%%%%%%%%
                 #################       %%%%%%%%%%%%%%%%%%%%
                   ##############       %%%%%%%%%%%%%%%%%%%
                     ###########       %%%%%%%%%%%%%%%%%%
                        #######       %%%%%%%%%%%%%%%%
                                    %%%%%%%%%%%%%%

                   | The OpenMC Monte Carlo Code
         Copyright | 2011-2016 Massachusetts Institute of Technology
           License | http://openmc.readthedocs.io/en/latest/license.html
           Version | 0.8.0
          Git SHA1 | aaa80eb98926a271b59df6b992a90c48df88d637
         Date/Time | 2016-08-23 06:44:19
```

### CODE REVIEW

**Comment by nelsonag** [comment]
It looks fine and everything, but is there anyway to decrease the size?  It
just looks huge in this email

**Comment by paulromano** [comment]
How's this?
```
                                %%%%%%%%%%%%%%
                          %%%%%%%%%%%%%%%%%%%%%%%%
                       %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                                   %%%%%%%%%%%%%%%%%%%%%%%%
                                    %%%%%%%%%%%%%%%%%%%%%%%%
                ###############      %%%%%%%%%%%%%%%%%%%%%%%%
               ##################     %%%%%%%%%%%%%%%%%%%%%%%
               ###################     %%%%%%%%%%%%%%%%%%%%%%%
               ####################     %%%%%%%%%%%%%%%%%%%%%%
               #####################     %%%%%%%%%%%%%%%%%%%%%
               ######################      %%%%%%%%%%%%%%%%%%%
               #######################      %%%%%%%%%%%%%%%%%
               ########################     %%%%%%%%%%%%%%%%%
                ######################     %%%%%%%%%%%%%%%%%
                 ####################     %%%%%%%%%%%%%%%%%
                   #################     %%%%%%%%%%%%%%%%%
                    ##############      %%%%%%%%%%%%%%%%
                      ###########     %%%%%%%%%%%%%%%%
                         #######      %%%%%%%%%%%%%%
                                    %%%%%%%%%%%%

                   | The OpenMC Monte Carlo Code
         Copyright | 2011-2016 Massachusetts Institute of Technology
           License | http://openmc.readthedocs.io/en/latest/license.html
           Version | 0.8.0
          Git SHA1 | aaa80eb98926a271b59df6b992a90c48df88d637
         Date/Time | 2016-08-23 07:13:38
```

**Comment by nelsonag** [comment]
That's better.  Probably can't go any smaller with the resolution that
terminal ASCII gives!

**Comment by samuelshaner** [comment]
Any chance you could add a vector graphic of the logo with this PR?

**Comment by nelsonag** [comment]
It looks like lines 2, 9, and 10 from the bottom have an extra blank space
between the 'wrench' and the 'bolt'.  Is that something we can clean up?

**Comment by paulromano** [comment]
@samuelshaner The .eps I have is 12 MB so I'd rather not include it in the repository. If you'd like, I can send it to you.

**Comment by paulromano** [comment]
Ok, here's the version that I just pushed:
```
                               %%%%%%%%%%%%%%%
                          %%%%%%%%%%%%%%%%%%%%%%%%
                       %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                                   %%%%%%%%%%%%%%%%%%%%%%%%
                                    %%%%%%%%%%%%%%%%%%%%%%%%
                ###############      %%%%%%%%%%%%%%%%%%%%%%%%
               ##################     %%%%%%%%%%%%%%%%%%%%%%%
               ###################     %%%%%%%%%%%%%%%%%%%%%%%
               ####################     %%%%%%%%%%%%%%%%%%%%%%
               #####################     %%%%%%%%%%%%%%%%%%%%%
               ######################     %%%%%%%%%%%%%%%%%%%%
               #######################     %%%%%%%%%%%%%%%%%%
               ########################     %%%%%%%%%%%%%%%%%
                ######################     %%%%%%%%%%%%%%%%%
                 ####################     %%%%%%%%%%%%%%%%%
                   #################     %%%%%%%%%%%%%%%%%
                    ##############      %%%%%%%%%%%%%%%%
                      ###########      %%%%%%%%%%%%%%%
                         #######      %%%%%%%%%%%%%%
                                    %%%%%%%%%%%%

                   | The OpenMC Monte Carlo Code
         Copyright | 2011-2016 Massachusetts Institute of Technology
           License | http://openmc.readthedocs.io/en/latest/license.html
           Version | 0.8.0
          Git SHA1 | aaa80eb98926a271b59df6b992a90c48df88d637
         Date/Time | 2016-08-23 09:27:54
```

**Comment by samuelshaner** [comment]
I see. Given the simplicity of the logo, I would have thought a vector graphic would have only been a couple hundred kB. If you could sent it to me, that would be great!

**Comment by paulromano** [comment]
Yeah, you'd think the size would be trivial. Not sure why it isn't...

**Comment by nelsonag** [comment]
Something is still off in the lower 1/3.  The bottom row looks to be a bit too long, and are rows 2,3,4 from the bottom missing a `#`?  (sorry! I know im being nitpicky!!)

**Comment by nelsonag** [comment]
Haha yes nelsoang is satisfied.  Thanks @paulromano!

**Pull request merged**
