### PR TITLE
Change default units of energy to electronvolts

### PR DESCRIPTION
**Pull request by paulromano**
This pull request changes the default units in OpenMC to eV rather than MeV which is used in the ACE format. I view eV as being the more natural unit, and to back that up I note that the ENDF format uses eV. When data is read in via `from_ace()` methods in the Python API, an `EV_PER_MEV` constant is used where needed. The HDF5 format now uses eV instead of MeV as well. Very few changes were needed in the Fortran code.

To comment on test results that changed:
- Some of the test results list energy group boundaries from Pandas dataframes, so those are now 1e6 higher.
- Any tests which contained the kappa-fission score now show results 1e6 higher.
- There are three tests which have legitimately different results (test_triso, test_quadric_surfaces, and test_asymmetric_lattice). I looked into these tests for quite a while and determined that there is no way to reproduce the earlier results. The problem stems from the fact that 1e6 has no exact binary representation since it is not a power of two; this causes the mantissa of the energy to be different in the 15th digit. If you simulate enough particles, eventually the error in the 15th digit can get amplified to the point where it causes divergence. For test_triso, this quite obviously happens because there are so many collisions in graphite. For test_quadric_surfaces, there are lots of reflective boundary conditions hit.

Two bugs that were also fixed:
- For the prompt and recoverable Q scores, it is possible for `score` to never be assigned while still scoring results. @smharper will understand the changes.
- Some numbers in `openmc.data.endf.SUM_RULES` disappeared at some point; it is now fixed.

Last point -- I added a version attribute in the HDF5 file so that attempting to use data files that are using an outdated format version gives a sensible error message.

### CODE REVIEW

**Comment by samuelshaner** [comment]
To your last point -- how does one add a version attribute to their hdf5 files? I just tried to run your branch and got the sensible error message:

    ERROR: HDF5 data does not indicate a version. Your installation of OpenMC
        expects version 1.x data.

**Comment by paulromano** [comment]
@samuelshaner Unfortunately there's no easy way to patch the data -- you will need to regenerate HDF5 files using `openmc-ace-to-hdf5` or directly from the API.

**Comment by paulromano** [comment]
I should have also mentioned if you are converting MCNP data we now have `openmc-convert-mcnp70-data` and `openmc-convert-mcnp71-data` scripts.

**Comment by samuelshaner** [comment]
Cool! I will mention that I have the hdf5 version of the nndc and MCNP cross section libraries. The scripts for converting the ace data to hdf5 can take a while to run (especially for MCNP xs). The xsdir file that comes with the nndc xs doesn't have a directory in it and fails when you run the `openmc-ace-to-hdf5` script on it. Since I have the new `cross-sections.xml` file, I can't use that with the script. I'm curious if there could also be a script that converts an existing hdf5 library to the current hdf5 library? I suspect this would just need to make a few modifications such as adding the `version` attribute and could be pretty quick.

**Comment by paulromano** [comment]
FWIW, with NNDC data I usually run:
```sh
find ... -name '*.ace' -o -name '*.acer' | sort | xargs openmc-ace-to-hdf5 -d nndc_hdf5
```

It would be nice to be able to convert existing HDF5 libraries to the current version, but in this case the changes are a little too complicated to handle easily. For many energy distributions, it's necessary to change both the outgoing energies and their probabilities (since they are per unit energy). Also, in order to have a "convert-old-to-new" functionality, we'd need to know what version the old one is, and right now all the old ones don't have any version information associated with them.

**Comment by smharper** [comment]
Thanks for catching the error in fission Q scores.

All the code looks pretty straightforward.  Merging

**Pull request merged**
