### PR TITLE
Two physics improvements and NNDC data fixes

### PR DESCRIPTION
**Pull request by paulromano**
## Physics Improvements

@makeclean did comparisons of flux spectra resulting from OpenMC, MCNP, and Serpent simulations of fixed source problems with a 30 cm sphere of a single nuclide, for each nuclide in ENDF/B-VII.1. These comparisons revealed that in many cases the three codes give different spectra. I've dug into the results a bit and have now identified two issues with OpenMC:

- N-15 uses histogram interpolation on incoming energy for a law 4 energy distribution. OpenMC did not support this but would just throw a warning and continue on. This PR adds support for histogram interpolation.
- The MT=5 reaction has an energy-dependent neutron yield for many nuclide/reactions in ENDF/B-VII.1. OpenMC was treating this reaction as always emitting one neutron. Nuclides that are afflicted by this include: all isotopes of Ca, Zr, Tm, W, Pb, and Mn-55, Co-58, Th-232, and Pa-233. This PR adds support for reading the energy-dependent neutron yields and using them for inelastic scattering reactions. Note that this now overrides the temporary fix in #296. Since Zr appeared in so many of the regression test suite problems, this PR includes new results for almost all tests. I've also bumped up the number of histories in test_reflective_cone to 1000 to prevent issues when running the test suite with many threads.

## NNDC Data

The NNDC cross sections have been updated to fix ZAID identifiers for metastable nuclides. The new data consistently uses base ZAID + 400 for a metastable nuclide, e.g. 95642 for Am-242m. It's important to note that before this, if you put Am-242m in a problem, OpenMC would actually give you Am-244m because they both had the same ZAID of 95249.

I've updated the default cross_sections_nndc.xml that is used by get_nndc_data.py, and I've also updated get_nndc_data.py to move files into the right directory (the new archive added an extra directory) as well as check the MD5 checksums, thereby protecting us if NNDC decides to change the data again.

I have the regression suite [running](http://openmc.mit.edu/cdash/index.php?project=OpenMC&date=2014-12-20&filtercount=1&showfilters=1&field1=site/string&compare1=63&value1=n018) now. **Note: you will need to download the new NNDC data to get the test suite working.**

### CODE REVIEW

**Comment by jdangerx** [comment]
Hey, I was just wondering if there's anything holding up this PR?

**Comment by makeclean** [comment]
Maybe just the outcome of my testing, which I will get to soon!

**Comment by makeclean** [comment]
Not that this should wait for me!

**Comment by paulromano** [comment]
Just waiting for a reviewer. Any takers? @nelsonag @bhermanmit @nhorelik @walshjon

**Comment by nelsonag** [comment]
I'm getting my system back in to shape here, if noone has taken it over by the time I get to it I'd be happy to handle it.

**Comment by paulromano** [comment]
I updated the error message per your suggestion. As for parsing the NNDC website to get the sums, I'd actually prefer to have us do it manually because we ought to know if/when the data changes! I'm afraid if we have the checksum fetched automatically, we won't be able to catch changes in the data.

Not sure if NNDC has plans to add more temperatures. My guess is a change like that wouldn't happen until the next release of ENDF.

**Comment by paulromano** [comment]
Just noticed that test_cmfd_jfnk currently fails when OpenMC is compiled with PETSc. The test results were updated using a non-PETSc executable, so I just need to re-generate this specific test with results from an executable with PETSc support.

**Comment by nelsonag** [comment]
@paulromano That's a reasonable stance on my md5sum parsing and temperature array comments.  

I just set up a simple model which exercises some of these features, results were as expected and when inspecting the values in memory they seem to make sense.  

Next, I ran the tests.  These are perfectly fine related to the changes in this test, but oddly, test_plot_basis fails in basic-debug and omp-debug but not basic-normal, basic-optimize, omp-normal, or omp-optimize.  There is some issue printing " Processing plot 1: 1_plot.ppm ...", with an error being thrown stating the following on line 226 of output.f90:
```Fortran runtime error: Substring out of bounds: upper bound (80) of 'message' exceeds string length (79)```
Oddly, I can only get to this failure (or any at all) while running the tests using the python scripts; taking the executable and directly running it yields no errors.  Is this the case with your runs?

Finally, I still need to set up PETSc, so maybe by the time you update your results I will have that all set up.

So, pending the PETSc changes and some further inspection in the test_plot_basis finding (which should be pulled in to a separate issue if it is anything), this ticket looks pretty close.

**Comment by paulromano** [comment]
Ok, I've fixed test_cmfd_jfnk, so I'm expecting everything should pass now.

I'm not seeing the same failure on test_plot_basis, e.g. see [here](http://openmc.mit.edu/cdash/testDetails.php?test=897361&build=11976). I have a feeling it has something to do with the length of the plot path being exactly 80 characters; can you try moving your openmc directory somewhere else and retrying?

**Comment by paulromano** [comment]
My running of the test suite [looks good](http://openmc.mit.edu/cdash/index.php?project=OpenMC&date=2015-01-21&filtercount=1&showfilters=1&field1=buildname/string&compare1=63&value1=physics).

**Comment by nelsonag** [comment]
Agreed.  Also, the test_plot_basis issue goes away when i move the directory higher up the tree (thus taking up less characters), as you suggested.

**Comment by nelsonag** [comment]
Somehow I always think of close instead of merge..

**Pull request merged**
