### PR TITLE
Fixes to documentation

### PR DESCRIPTION
**Pull request by paulromano**
This pull request makes a few changes:

- Only the current revision of the statepoint and voxel file formats is documented rather than all being listed.
- A few fixes were made so that 'make latexpdf' works correctly. This will allow us to build PDF documentation that can be posted on the github releases page.
- I've added a section to the style guide for Python code since it is becoming increasingly common. 

@wbinventor I'd appreciate your looking at the changes to the style guide to make sure you don't have any issues with it, seeing as though you've already written our Python API!

### CODE REVIEW

**Comment by bhermanmit** [comment]
Some comments:

- source/devguide/styleguide.rst:154: ERROR: Unknown target name: "nummpydoc".
     - nummpydoc should be numpydoc
- at the bottom of style guide, links are missing to PEP8, numpydoc, numpy, scipy, h5py
- In workflow.rst update package versions -
     - MPI_DIR='/opt/mpich/3.1.3-gnu'
     - HDF5_DIR='/opt/hdf5/1.8.14-gnu'
     - PHDF5_DIR='/opt/phdf5/1.8.14-gnu'
     - PETSC_DIR='/opt/petsc/3.5.2-gnu'

**Comment by bhermanmit** [comment]
Comments on pdf:

- Should we point our that inkscape is needed to make pdfs of some images?
- Should we have another level of bookmarks in the pdf?
- Numbering starts at subsection level, can we make them sections?
- Should we number equations in introduction/overview part of theory
- Master slave diagram figure numbering messed up, Figure 1.5, 1.6...
- Equation 1.197, CMFD interior cell eq. too wide
- References after each theory topic are not showing up
- Some source code in data extraction section overflow, around PDF page 110
- Bibliography randomly put at end of pdf
- Index at end of pdf can be removed

**Comment by paulromano** [comment]
@bhermanmit To respond to your comments:

- Currently we don't discuss anywhere requirements for building the documentation, so I'd say let's hold off on mentioning inkscape until we actually have something talking about doc build requirements.
- I added two more levels of bookmarks.
- I couldn't figure out a way to change the numbering.
- No need to number equations unless they are cross referenced.
- Master-slave figure numbering fixed.
- Equation 1.197 fixed.
- Not sure how to get references to show up after each section rather than the end.
- Prevented overflow on the source code by starting it with `statepoint_3d.py`.
- Couldn't figure out how to remove index.

There's only so much configuration I have control over since Sphinx generates the latex files based on the rst files and a few options. I can add things to the latex preamble, but that's about it.

**Comment by paulromano** [comment]
@bhermanmit Are you satisfied with my changes?

**Comment by bhermanmit** [comment]
I still want to look at the following:
1. In Table of Contents make contents chapter an I
2. Display table of contents by section number and add more levels
3. Make equations numbers and figure numbers either independent of chapter or make them dependent on section number
4. See if I can add the appropriate references in after the References subsection or elimnate this
5. Double check references, there may be an issue with using the bibtex sphinx package https://sphinxcontrib-bibtex.readthedocs.org/en/latest/usage.html#known-issues-and-workarounds

Let me know if disagree with anything or don't think it's a big deal.

**Comment by bhermanmit** [comment]
I also want to check out https://github.com/jterrace/sphinxtr and see how our documentation looks.

**Comment by paulromano** [comment]
I've added one more level in the table of contents and made the equation numbers depend on the section. As far as the references, right now I am not using sphinxcontrib-bibtex. That would probably be a  better solution but outside the scope of this PR. I also have a preamble line that uses roman numerals for chapters as you suggested, but I commented it out because I didn't think it made it look better.

**Comment by bhermanmit** [comment]
Looks great, thanks @paulromano!

**Pull request merged**
