### PR TITLE
Bugfix for short tracks near tally mesh edges

### PR DESCRIPTION
**Pull request by smharper**
This should fix the error that @RonRahaman posted to the [user's group](https://groups.google.com/forum/#!topic/openmc-users/qARnMlKV-uo).  Can you verify it, @RonRahaman?

I also made some small readability changes to the MeshFilter code while I was there.

### CODE REVIEW

**Comment by smharper** [comment]
Some details about the bug in case anyone in the future (perhaps myself) needs to know:

This error was discovered for a case where a cylinder was perfectly inscribed in a box that was overlayed with a tally mesh.  In this case, there are small regions where the box, cylinder, and mesh boundaries all intersect.  A neutron can travel a very short distance in the narrow gap between the cylinder and box near the singularity.  If that distance is less than `TINY_BIT` then the code
```F90
      xyz0 = p % last_xyz + TINY_BIT * p % coord(1) % uvw
      xyz1 = p % coord(1) % xyz - TINY_BIT * p % coord(1) % uvw
      call get_mesh_indices(m, xyz0, ijk0(:m % n_dimension), start_in_mesh)
      call get_mesh_indices(m, xyz1, ijk1(:m % n_dimension), end_in_mesh)
```
will actually think that the neutron starts just outside of the mesh and travels into it.  This chunk of code will pick an `ijk0` and an `ijk1` that are in the order _opposite_ to the neutrons direction of travel.  In other words, this part thinks the neutron is traveling backwards.

Since the particle appears to start outside of the mesh, the code will then search for the first mesh cell that the particle encounters.  But it starts looking with a cell just outside the mesh, and then keeps looking in the direction the particle is traveling, i.e. at cells even farther outside the mesh.

**Comment by RonRahaman** [comment]
@smharper, sure, I will see if it fixes my problem

**Comment by RonRahaman** [comment]
Looks like it's working for my geometry.  Thanks!

**Comment by smharper** [comment]
Thanks for verifying the fix, @RonRahaman!

**Comment by paulromano** [comment]
Thanks @RonRahaman for reporting and @smharper for fixing!

**Pull request merged**
