### PR TITLE
Additions in openmc.capi and elsewhere

### PR DESCRIPTION
**Pull request by paulromano**
The major new feature in this pull request is to run OpenMC in a batch-by-batch fashion using the openmc.capi package. It introduces new functions `next_batch` and `iter_batches` which simulate a single batch and iterate over batches, respectively. The `iter_batches` function allows one to run Python code inbetween batches. I've been using this function to perform tally convergence checks that are more complex than what can be handled with our Fortran-side tally triggers. Along with these two functions, I've introduced `simulation_init()`, which allocates memory for tally results, the source bank, etc. (things that *are not* performed by `init()`) and a corresponding `simulation_finalize()` which deallocates them. Thus, a script to perform some arbitrary convergence check looks like:

```Python
openmc.capi.init()
openmc.capi.simulation_init():
for _ in openmc.capi.iter_batches():
    if converged():
        break
openmc.capi.simulation_finalize()
openmc.capi.finalize()
```

where `converged()` is an arbitrary function that performs a convergence check.

This PR also has an assortment of other changes/improvements/additions:

- `openmc.capi.Tally` has been significantly enhanced. It's now possible to look at tally means and standard deviations in real-time.
- Exposed C API functions for inspecting the source bank.
- Exposed a C API function for writing a statepoint (and can specify filename!)
- I recently ran into an issue trying to export a huge model (one with 19 million materials) and I found that sorting XML elements turned out to be very expensive. I've improved this by performing sorting before XML elements are actually created (ergo, `sort_xml_elements` is no longer)
- I've moved get_rectangular_prism into the openmc.model package and added a new `subdivide` function which creates regions given a sequence of surfaces.
- Some simple optimizations of `Universe.determine_paths`
- I've changed how k-effective and entropy are stored (they are now vectors) so that a simulation controlled from the C API can proceed as long as it needs without needing to know a maximum number of batches.

@smharper would you care to review?

### CODE REVIEW

**Comment by paulromano** [comment]
I've added a whole bunch of unit tests for the openmc.capi package since it is not tested via the regression suite at all. You can see in the Travis output that coverage for openmc.capi is around 90%. Our overall coverage is still very low (24%) but it doesn't account for what's being tested in the regression suite.

**Comment by smharper** [comment]
Out of curiosity, can you run Python on BGQ?  I really like all the runtime Python features we're adding, but I'm trying to decide if I should avoid getting too attached to them in my own calcs.

**Comment by paulromano** [comment]
We have other problems on BG/Q -- last time I checked I couldn't compile with the IBM compilers, which is what I had been using. It probably is more of a pain in general because BG/Q doesn't deal well with shared libraries. However, I can tell you that I'm using these runtime features in the Python API on other supercomputers (NERSC Cori and ALCF Theta) with few issues. I think at this point, there are enough codes dependent on Python that most supercomputer centers commit to supporting Python.

**Comment by smharper** [comment]
Awesome.  Good to know!

**Comment by smharper** [comment]
I like the looks of this so far.  Here's some feedback from my first pass:
* The only place where we reduce our MPI tally results is in state_point.F90, right?  We should probably add an API function so that tallies can be reduced early for convergence checking.  Ideally, we would be able to reduce just one tally.
* Add a helpful error message to `openmc_get_keff` for `n_realizations <= 3`.  That's a natural thing to want to want to check during the inactives (or within the first three active generations).
* If you call `iter_batches` without first calling `simulation_init`, an unhelpful error message is provided.  We should probably add a graceful error for this as well.

**Comment by paulromano** [comment]
Thanks for the comments @smharper. To address your points in order:

- Tallies are actually reduced at the end of every batch, so nothing extra is needed. At the end of a simulation, they are broadcasted to every process, so the key thing to remember is that if you are checking convergence at runtime and you are using MPI, the check has to be done on the master process (and a resulting logical broadcasted to other processes).
- Very good point about `capi.keff()`. I've improved it so that you can check it at any point. When n <= 3, you're really getting the tracklength estimate (which matches the normal OpenMC standard output) and then it switches over to the combined estimator at n == 4. During inactive batches and for n == 1, the standard deviation comes back as infinity, which I think makes the most sense.
- I've fixed the unhelpful message when `iter_batches` (really `next_batch`) is called before the simulation is initialized. The return value of `openmc_next_batch` is a little messy right now but we can fix that later.

**Comment by smharper** [comment]
Another great API addition.  Thanks @paulromano!

**Pull request merged**
