### PR TITLE
Some bug fixes for volume calculations

### PR DESCRIPTION
**Pull request by paulromano**
In addition to fixing bugs, this PR enables one to get microscopic MGXS over a universe, which was not possible before.

### CODE REVIEW

**Comment by wbinventor** [comment]
This looks good to me and I am going to merge it in now. I do have two follow-on questions: would it be reasonable to perform a stochastic volume calculation over each mesh cell in a tally mesh, to extract nuclide atom densities? It seems that your stochastic volume calculator has advanced to the point where it might not be so difficult to implement this, if it can't already be done.

**Comment by paulromano** [comment]
Thanks once again my friend. Meshes would be a little bit more complicated as they would require extra logic on both the Fortran side and Python side. I'll look into it though and see how difficult or easy it would be. Do you know of someone wanting such a capability?

**Comment by wbinventor** [comment]
Yeah, it would be useful to generate microsocopic MGXS on a mesh. I've been helping @tjlaboss get started with this since he needs to compute micro MGXS on a mesh as part of his research. And I think many others would be interested in this as well...perhaps more than those who might use the material, cell or universe spatial domains for MGXS generation. Don't bump this up as a priority, but perhaps we can open up an issue for it if you think it might be worthwhile to implement in the future.

**Comment by paulromano** [comment]
Cool, didn't realize it wasn't just an esoteric idea. Definitely feel free to open up an issue.

**Pull request merged**
