### PR TITLE
Drop support for Python 2

### PR DESCRIPTION
**Pull request by paulromano**
This pull request removes support for Python 2.7 and makes Python 3.4+ a requirement. Most of the changes are pretty straightforward (removing `__future__` and changing imports, using `super()`, etc.). I've also removed a number of deprecated methods that have been hanging around for a while. The primary motivation for this PR is an upcoming pull request that would merge OpenDeplete into OpenMC as a new `openmc.deplete` package.

### CODE REVIEW

**Comment by smharper** [comment]
There's a few `super`s to update in our test suite.

By the way, I switched the Coveralls setting so that it doesn't leave PR comments.  I think they'll just be unnecessary clutter since you can easily click the "Details" option at the bottom of the PR to get the same info.

**Comment by paulromano** [comment]
Thanks for pointing out the `super`s from tests. Those are fixed now.

**Comment by smharper** [comment]
Looks good.  Merging!

**Comment by paulromano** [comment]
@smharper really appreciate all the quick reviews; thanks!

**Comment by smharper** [comment]
You're welcome!

**Pull request merged**
