### PR TITLE
Make data scripts available when installing

### PR DESCRIPTION
**Pull request by paulromano**
This PR addresses #730 and #731 brought up by @scopatz. All the scripts in the data/ folder have been moved to scripts/ and renamed. The scripts will now be installed so that a user doesn't have to have the source just to get HDF5 data. I've also updated the docs with instructions on using conda-forge.

As I was going through the scripts, I decided to make judicious use of `six` there and elsewhere. Most of the changes have to do with using metaclasses properly (six.add_metaclass) and checking for strings (six.string_types). This avoids a lot of the ugly `if sys.version_info...` statements you see peppered throughout the code.

@scopatz If you have a moment, please take a quick look at the changes relevant to your issues and let me know if you are satisfied.

### CODE REVIEW

**Comment by scopatz** [comment]
Hi @paulromano - thanks for putting this in!  My quick checks all passed. I can do a more in-depth review tomorrow if you'd like. Otherwise I think it is good to go.

**Comment by smharper** [comment]
This branch needs a merge from develop.  Also, it's a little weird that the "data" directory is empty except for the fission_Q data.  Maybe stick a readme in there to let users know about the `openmc-get-*` scripts.  Other than that, the changes look fine and I'll be happy for a merge.

**Comment by paulromano** [comment]
Thanks for reminding me about the fission Q data file -- I think it does need to find a new home (at the very least `openmc-get-nndc-data` needs to know where to find it).

**Comment by paulromano** [comment]
Ok, I ended up moving that file to `openmc/data`, having `setup.py` install it as data thus making it available to openmc-get-nndc-data.

**Comment by paulromano** [comment]
@smharper do you have any outstanding requests for this PR?

**Comment by smharper** [comment]
Nope, no requests.  Sorry to leave this dangling

**Pull request merged**
