### PR TITLE
Atomic masses in Python API

### PR DESCRIPTION
**Pull request by paulromano**
This pull request simply adds an `atomic_mass` function to the `openmc.data` package. It uses data from AME2012, which is stored locally. A dictionary is populated at the first invocation of `atomic_mass` and after that, the only cost is a hash lookup.

I've also updated the `ATOMIC_SYMBOL` dictionary with the proposed IUPAC names for elements 113 and 115-117... since everyone needs to know the mass of Oganesson-295!

### CODE REVIEW

**Comment by smharper** [comment]
What's the use case for this?  For anything transport related, we already have the AWR in the cross section files.

**Comment by paulromano** [comment]
Can be useful in input preparation if you need to know the atomic mass of some isotope for whatever reason and you don't want to load nuclear data from ACE, HDF5, or ENDF files. We could also use it to enable specifying elements by weight percent from the Python API.

**Comment by smharper** [comment]
Strip metastable info from the isotope name.  (The masses will technically be wrong for metastables, but the difference is negligible for any use I can think we'd be interested in.)  That way users will be able to loop over materials with metastables without have to add pre-processing steps.

**Comment by smharper** [comment]
Looks good.  Merging!

**Pull request merged**
