### PR TITLE
Remove use of PETSc for CMFD

### PR DESCRIPTION
**Pull request by paulromano**
This pull request removes the option to use PETSc for CMFD calculations. Since there is a built-in solver, the PETSc solvers add limited value. If I understand correctly, @bhermanmit found in his studies that parallelism did not help with the linear solves. Given the limited value and extra software complexity, I believe that removing the use of PETSc altogether will help us improve the maintainability of OpenMC.

To summarize some of the salient changes:
- The cmfd_power_solver, cmfd_jfnk_solver, and cmfd_slepc_solver (never used) modules were removed entirely
- The ksp_monitor, snes_monitor, and solver user input options were removed.
- The JFNK solver test was removed.
- No PETSc test configurations exist any more.
- A function to calculate the transpose of a CSR-format sparse matrix was added since the only transpose functionality relied on PETSc. At present, transpose is only used to calculate mathematical adjoints, which are not used by default. If the user requests the adjoint, they get the physical adjoint.

@bhermanmit I can't imagine anyone other than you reviewing. Let me know if you are willing and when you think you could take a look.

If anyone is using PETSc for CMFD and prefers that it stay in the code, now would be a good time to speak up!

### CODE REVIEW

**Comment by bhermanmit** [comment]
Sure, I will have it reviewed by Friday. Let me know if you want it in faster than that.

**Comment by bhermanmit** [comment]
Code looks good! Glad all the warnings are resolved. Can you fix the memory leak introduced by the tally trigger stuff. You can see if from the CDash (remove-petsc tests). I hope I can then resolve the one induced by the cmfd test after this PR is merged.

**Comment by paulromano** [comment]
Ah, missed that leak when I was reviewing the trigger PR. That last commit should fix it hopefully.

**Comment by wbinventor** [comment]
Just saw this - you can kill my PR if you like your fix better.

**Comment by bhermanmit** [comment]
Thanks @paulromano! Looks like it worked, CDash shows it back at 4. I will merge once Travis has run.

**Comment by wbinventor** [comment]
On a related note, is there a way for us developers to run our forks/branches through CDash?

**Comment by bhermanmit** [comment]
Yes, you can always run the test suite locally if you go into the tests folder.

python run_tests.py -s

The -s runs CTest in script mode and does everything except push results to the CDash.

To push your results up to the CDash we need to get you set up with an account, then you would do:

python run_tests.py -D Experimental -p "{name of branch}"

I will get you access soon.

________________________________

**Comment by wbinventor** [comment]
Oh wow, this is much easier to do than I realized! Thanks @bhermanmit

**Comment by bhermanmit** [comment]
Looks like tests didnt pass, I will do some digging, but I could not replicate them on the CDash.

**Comment by paulromano** [comment]
I had to restart a few times to get it to pass. Each time the failures were random, so I'm inclined to say its a Travis issue, not an OpenMC issue (especially given that you couldn't replicate it locally).

**Pull request merged**
