### PR TITLE
Change default optimization level for gcc

### PR DESCRIPTION
**Pull request by paulromano**
I didn't realize until recently that not specifying optimization when using the gcc compiler defaults to no optimization at all. There is a big difference in performance when using -O2 vs -O0, so this pull request simply changes the default when compiling OpenMC with gcc to use -O2. Using `-Doptimize=on` will still use -O3.

### CODE REVIEW

**Comment by smharper** [comment]
Why don't we have `-Doptimize=on` by default?  Also, do we want to switch back to `-O0` for `-Ddebug=on`?

**Comment by paulromano** [comment]
We don't have optimize on by default because generally once you get up to O3, the compiler starts to make optimizations that could impact correctness, e.g., assuming it doesn't really have to stick to IEEE 754. You're right about debug though, I'll remove -O2 for debug.

Separate question -- do you remember why we removed LTO for optimize?

**Comment by wbinventor** [comment]
Yeah, I'd like to use `-Doptimize=on` as well. Most users IMHO don't know or use our various compile-time options, and this one could save a lot of folks a lot of time.

**Comment by paulromano** [comment]
@liangjg can attest that there's not too much difference in performance between O2 and O3, so having O2 by default will already save folks time.

A separate question in my mind is whether to turn OpenMP on by default. I originally was against this but I'm starting to reconsider.

**Comment by wbinventor** [comment]
Good point about -O2 vs. -O3. I'm all in favor of turning on OpenMP by default.

**Comment by smharper** [comment]
That's not true for GCC, right?  AFAIK the correctness-risky stuff only happens for `-Ofast`

I am also okay with `-Dopenmp=on` by default

**Comment by paulromano** [comment]
@smharper That does appear to be correct. Taking a look at the man-page, risky options are only on for `-Ofast`. So, we could in theory turn on `-O3` by default and `-Ofast` for optimize mode. However, it does look like `-Ofast` changes test results... hmmm

**Comment by smharper** [comment]
I don't feel a particular need to go to `-Ofast`.  I think I tried it one time and found basically no runtime improvement, and breaking reproducibility can be pretty annoying.

Regarding `-flto`, I just searched through our Hangouts chat and apparently it had something to do with weird HDF5 errors.

**Comment by paulromano** [comment]
Ok, let's just leave default at O2 and optimize at O3 for the time being then.

**Comment by liangjg** [comment]
@paulromano how about adding lines in CMakeLists.txt to print the flags? Like,
``` sh
message(STATUS "fortran flags: ${f90flags}")
message(STATUS "c flags: ${cflags}")
message(STATUS "ld flags: ${ldflags}")
```
which will print messages like
```
-- fortran flags: -cpp;-std=f2008;-fbacktrace;-O2;-fopenmp
-- c flags: -cpp;-std=c99;-O2;-fopenmp
-- ld flags: -fopenmp
```
It may be useful for the user to check what compiler flags has been enbaled.

**Comment by paulromano** [comment]
Good idea @liangjg. I've added that in.

@wbinventor @smharper I've turned on OpenMP by default now.

**Comment by wbinventor** [comment]
I'm satisfied with this PR. Thanks @paulromano and @liangjg!

**Pull request merged**
