### PR TITLE
Polymorphic tallies

### PR DESCRIPTION
**Pull request by smharper**
This PR adds the `TallyContainer` class which contains objects of the class `TallyObject`.  This will allow us to more easily add new tally functionality that requires extending `TallyObject`.  This is analogous to the `Lattice` and `LatticeContainer` types.

In the near future, I plan to implement differential tallies using an extension of `TallyObject`.  I also expect that a polymorphic `TallyObject` will be helpful over the course of the tally refactoring.

This PR doesn't actually change any functionality so I'll understand if you'd rather not review it now and wait until I've added more, but I would prefer to implement differential tallies and the tally refactor through a bunch of smaller, incremental PRs like this one rather than with a big, monolithic PR.  I think the small PRs will make it easy for me to keep up with the develop branch and make it easier for you guys to review my work.  Do you agree with this thinking?

### CODE REVIEW

**Comment by wbinventor** [comment]
@smharper I definitely agree that smaller "piecewise" PRs are superior to a large PR for the tally refactoring IF there is an overarching design/scheme that you have in mind for the final result. I'll help review this PR early this week, though I don't know that I want to assume responsibility considering my limited knowledge of Fortran.

**Comment by smharper** [comment]
RE: overarching design/scheme

I am pretty certain that I will implement differential tallies using something that looks very similar to

```fortran
type, extends(TallyObject) :: DiffTallyObject
  real(8) :: accumulator
  integer :: dependent_variable
  integer, allocatable :: dependent_variable_bins(:)
  type(TallyResult), allocatable :: diff_results(:,:)
```

For the refactor, I will admit that I don't yet have a very precise plan going forward.  But until I do have such a plan, I am working off of @bhermanmit's tally_refactor branch which uses a polymorphic `TallyClass` that seems to be a new form of the `TallyObject` type.

**Comment by wbinventor** [comment]
If I recall, there was a tentative plan to collaboratively design the refactored tally system using some cloud service like [Gliffy](https://www.gliffy.com/) or [draw.io](https://www.draw.io/). If you're still interested in doing this, I'll be happy to help with the design since I'm certainly interested in making this refactor happen.

**Comment by paulromano** [comment]
Smaller PRs are always easier to review than one large monolithic PR, so I'm all for smaller PRs. However, each one should have a specific purpose. As is, I'd prefer to start reviewing this one once it is to the point where polymorphism is being taking advantage of.

**Comment by paulromano** [comment]
I think @bhermanmit did start some class diagrams on a cloud service. I'll let him comment further.

**Comment by bhermanmit** [comment]
I am still looking for an alternative, I really like the http://www.genmymodel.com/, but the free version doesn't allow us to do too much. So if we can get someone to put down $5 a month we can all the nice features. @wbinventor feel free to setup one of the other ones and we can start designing if you like them better.

**Comment by nelsonag** [comment]
I'm on the fence on this one.  Smaller PRs are always better for reviewing, yes.  But I still have my NDPP pull request in queue (though I have to update it to take advantage of the simplified tally scoring lookup refactor), and if this comes in little chunks that takes a long time to implement, I may be waiting a good long while from this point to get that PR in since it likely touches all the same lines of code I've touched.  

To that end, if this was in smaller PRs, what would be the 1) timeline, and 2) order of changes to be made?  I began this comment with selfish reasons (my PR), but really I think these items are ones we should know in advance.

**Comment by wbinventor** [comment]
@nelsonag - I can certainly "feel your pain" by constantly having to update longstanding PRs to the latest version of the develop branch. However, for what it's worth, my two cents is that the tally refactorization is should proceed ahead of NDPP *if* @smharper had a relatively short timeline in mind (*e.g.*, 3-4 months). I'm not sure how many other users have tried using NDPP, but I've found it difficult, and it does not work out-of-the-box with the NNDC cross-section data. For this and other reasons, I personally think that the NDPP framework should mature a bit before being merged into the core of OpenMC. The tally refactoriztion, on the other hand, has the potential to greatly benefit not just the dev team, but users if it boosts performance (which I believe it will) in the shorter term. Plus, the refactor will make it much easier for developers to implement new types of tallies - and hopefully your NDPP tallies transfer easily into the new framework. I know that this is an aside from the question about small vs. large PRs  but wanted to put in my preference to move forward with @smharper changes.

**Comment by smharper** [comment]
Okay it looks like this PR is jumping the gun a little bit.  Please bear with me as I try to find the right balance here.  I'll close this one for now and come back to it when I've developed it a bit further.

**Comment by nelsonag** [comment]
@wbinventor Don't forget the out-of-the-box issues were due to using an outdated branch.  The issues of inconsistent significant digits of kTs in the ACE/NDPP files and the *.xml files should be fixed by now.  Regardless, let me know what other difficulties you've found.

**Pull request closed without merging**
