### PR TITLE
Improvements to CMakeLists.txt

### PR DESCRIPTION
**Pull request by paulromano**
After spending a full day reading "Mastering CMake" and a whole bunch of blog posts, I decided to take a stab at improving our CMakeLists.txt file. The following things have been changed:

- "Vendored" dependencies (i.e., dependencies that we have bundled alongside our codebase) have been moved to a separate `vendor/` directory. This includes pugixml and the Faddeeva package. Each dependency gets built as its own library. Any interface code that is written on top of those lives in the main `src/` directory and is built as part of libopenmc.
- It is a best practice to specify whether compile flags/definitions/includes are needed only to build a library or if they are also needed for another target that depends on the library. Before, many of our compile flags/definitions were getting set globally rather than being applied to specific targets. I've changed it to be more systematic, e.g. the `-DUNIX` definition is only needed by libopenmc, not everything.
- Use `FindOpenMP` that is built-in to CMake to determine appropriate flags for using OpenMP. This requires bumping our minimum CMake version to 3.1.
- Use the `$<COMPILE_LANGUAGE>` generator expression to apply C++ and Fortran build flags separately. This requires CMake 3.3.

I'm personally comfortable with updating the required version to 3.3, which has been around for three years.

I also made a few small doc fixes in this PR and removed some "dead" code on the Fortran side (doppler.F90 which has never been used, and two bound procedures relating to ACE data).

### CODE REVIEW

**Comment by paulromano** [comment]
One other thing I forgot to mention -- I modified our dictionary of thermal scattering names to support converting the new [Lib80x library from LANL](https://nucleardata.lanl.gov/ACE/index.html).

**Comment by smharper** [comment]
Everything here looks good, just one small question: is the directory name "vendor" a standard?  To me the word "vendor" implies purchase, and "third_party" feels a little more commonly used in the open source software field.  I tried skimming through a couple other project's source trees, but to me it looks like there is no widespread standard.

**Comment by paulromano** [comment]
The term "vendoring" is pretty standard, but you're right that other terms are also commonly used. I picked "vendor" because it has a specific meaning in that when one says that software dependencies are vendored, it means that they are directly included in the source tree (as opposed to being linked through a git submodule).

**Comment by smharper** [comment]
Good to know.  Thanks, @paulromano

**Comment by paulromano** [comment]
Thanks for reviewing @smharper!

**Pull request merged**
