### PR TITLE
Replicated MGXS Subclass Docstrings

### PR DESCRIPTION
**Pull request by wbinventor**
This PR replicates the class docstring for `MGXS` within each of its subclasses. This allows one to inspect the attributes/properties of the class within IPython or Jupyter Notebook. This PR builds upon #644 and should be reviewed after it is merged.

### CODE REVIEW

**Comment by paulromano** [comment]
@wbinventor Can you remove the docstrings on MGXS.xs_tally(), MGXS.tallies(), and Chi.xs_tally()? They cause cross-reference issues when building the documentation.

**Comment by wbinventor** [comment]
@paulromano I'm only seeing cross-reference issues for `MGXS.xs_tally`. I just pushed, can you test this out and see if you are still seeing issues for `MGXS.tallies` and `Chi.xs_tally`? I don't see why there should be any issue for the former since it is a property only defined once in `MGXS`, and the latter shouldn't be a problem given that I just removed the docstring from the parent class property.

**Comment by paulromano** [comment]
For those other two, it's not so much that it creates conflicting cross references, but it just creates entries that are redundant. For xs_tally, it is definitely wrong because, e.g., a hyperlink is created from xs_tally in the variables section of AbsorptionXS to Chi.xs_tally. In general, it is inconsistent because we don't have docstrings attached to any other property definitions.

**Comment by wbinventor** [comment]
Oh I see. Alright I just removed those docstrings as well.

**Comment by paulromano** [comment]
@wbinventor Did you push? I don't see it.

**Comment by wbinventor** [comment]
Oops, I got distracted - here it is.

**Comment by paulromano** [comment]
Thanks!

**Pull request merged**
