### PR TITLE
Update quickinstall clone URL

### PR DESCRIPTION
**Pull request by scopatz**

### CODE REVIEW

**Comment by wbinventor** [comment]
Thanks for the fix @scopatz.

**Comment by paulromano** [comment]
I thought ssh protocol won't allow anonymous access??

**Comment by scopatz** [comment]
Oh right, I am not sure it does.  However, the protocol that was there was just hanging until timeout (2 min?).  I think the right protocol for anonymous is HTTPS (https://github.com/mit-crpg/openmc.git)

**Comment by paulromano** [comment]
I would agree https is probably best. I'll go ahead and change it on the develop branch.

**Pull request merged**
