### PR TITLE
Fix bug tallying reaction rates with multipole

### PR DESCRIPTION
**Pull request by paulromano**
This pull request addresses the bug described in #853. I've extended the multipole test to include some tallies too so we cover the case that produced the bug in the first place.

Unrelated to the multipole fix -- I've changed how pugixml is built (always assuming the C++ compiler has long long support). The problem is that when you use the CXX_STANDARD target property in CMake, it doesn't necessarily know what flags to use for all compilers. For example, I've found that for both the IBM XL compilers and PGI compilers, it doesn't work.

### CODE REVIEW

**Comment by wbinventor** [comment]
It looks like "test_diff_tally" now fails.

**Comment by paulromano** [comment]
Oops, just fixed test_diff_tally.

**Comment by wbinventor** [comment]
Alright. I'll let @cjosey take the lead on this. Thanks for putting together a patch for #853 so fast.

**Comment by cjosey** [comment]
I looked through it.  I am a bit concerned in setting ``temp_index`` to ``-1`` to indicate multipole to force segfaults down the line, but this isn't new to this release.

I ran the ``test_multipole``, with both ENDF and multipole libraries, modified to run at 296.4 K and with way more neutrons/batches.  Here's the results. 

ENDF:
```
 ==========================>     TALLY 10000     <==========================

 U235
   Total Reaction Rate                  0.777623       +/- 4.79381E-04
   Fission Rate                         0.560464       +/- 3.86512E-04
   (n,gamma)                            0.108167       +/- 7.86756E-05
   (n,elastic)                          9.35008E-02    +/- 4.12865E-05
   (n,p)                                0.0            +/- 0.0
 O16
   Total Reaction Rate                  4.54104        +/- 1.20199E-03
   Fission Rate                         0.0            +/- 0.0
   (n,gamma)                            1.38118E-04    +/- 5.11605E-08
   (n,elastic)                          4.53666        +/- 1.19712E-03
   (n,p)                                1.21498E-05    +/- 3.98886E-07
 Total Material
   Total Reaction Rate                  72.6138        +/- 2.70804E-02
   Fission Rate                         0.560464       +/- 3.86512E-04
   (n,gamma)                            0.437178       +/- 1.84012E-04
   (n,elastic)                          71.5964        +/- 2.69158E-02
   (n,p)                                1.21498E-05    +/- 3.98886E-07
```
Multipole
```
 ==========================>     TALLY 10000     <==========================

 U235
   Total Reaction Rate                  0.777590       +/- 4.98196E-04
   Fission Rate                         0.560460       +/- 4.23013E-04
   (n,gamma)                            0.108174       +/- 7.73689E-05
   (n,elastic)                          9.34555E-02    +/- 3.41705E-05
   (n,p)                                0.0            +/- 0.0
 O16
   Total Reaction Rate                  4.54328        +/- 1.31510E-03
   Fission Rate                         0.0            +/- 0.0
   (n,gamma)                            1.38205E-04    +/- 5.43364E-08
   (n,elastic)                          4.53890        +/- 1.31326E-03
   (n,p)                                1.16251E-05    +/- 4.21486E-07
 Total Material
   Total Reaction Rate                  72.6361        +/- 3.08601E-02
   Fission Rate                         0.560460       +/- 4.23013E-04
   (n,gamma)                            0.437289       +/- 2.02761E-04
   (n,elastic)                          71.6186        +/- 3.06089E-02
   (n,p)                                1.16251E-05    +/- 4.21486E-07
```
They're within uncertainty of one another.  I consider this good and am merging.

**Pull request merged**
