### PR TITLE
Fix a few issues with MGXS documentation

### PR DESCRIPTION
**Pull request by paulromano**
Issues I've fixed:

1. Docstrings in `openmc.mgxs_library` classes were incomplete
2. Documentation of `openmc.mgxs_library` wasn't viewable in our generated Python API docs
3. Prevent `<default_xs>` from being written to materials.xml if it's None.

@nelsonag or @wbinventor would both be qualified reviewers

### CODE REVIEW

**Comment by nelsonag** [comment]
The code itself looks good to me, but I haven't had a chance yet to compile the docs and view them myself.

**Comment by nelsonag** [comment]
Sigh I cant build these, or any docs, so well anymore apparently.
Is there a specific package you need for extension notebook_sphinxext?  There seem to be a few with similar functionality (convert notebooks to rsts).

**Comment by paulromano** [comment]
Oh, the issue is that you need to have Jupyter 4.0+ installed. Really, it's the nbconvert package you need, but that's part of Jupyter.

**Comment by nelsonag** [comment]
Odd, I have 4.1 installed.
I'm willing to bet this is a python2 vs 3 issue then.  I have to change the
Makefile to look for sphinx-build2 to avoid getting recursion errors.  So
I'm betting something else along the way is calling my system's python
command instead of python2 that changing the makefile cant capture.  That's
my guess anyways. I have no real idea.

**Comment by paulromano** [comment]
Hmm, I've run into issues with sphinx-build and Python 2/3 before too, but don't recall what the resolution was. I'd suggest using virtualenv or conda to create an isolated environment.

**Comment by nelsonag** [comment]
I set up a conda environment and it seems to work @paulromano.  Thanks!
Am I the only one who has been using system packages for my pythoning, and everyone else uses conda?

**Comment by nelsonag** [comment]
Looks good to me! Thanks @paulromano

**Comment by wbinventor** [comment]
I just recently started using conda and have found it to be superior to
apt-get at leadt. It has a much wider variety of more up-to-date packages,
along with nice features to switch between multiple environments. I'm sure
there are probably some disadvantages as well, but I haven't yet found them.

**Pull request merged**
