### PR TITLE
New logo!

### PR DESCRIPTION
**Pull request by paulromano**
This pull request adds our new logo to the documentation. The new logo is:

openmc_logo

and here's how it looks in our RTD documentation:

screenshot from 2016-08-20 16-31-47

Two other little documentation-related bugs are fixed as well.

### CODE REVIEW

**Comment by paulromano** [comment]
P.S. If you like the new logo, you can thank @bforget for funding a logo competition!

**Comment by wbinventor** [comment]
Woot, looking slick!

**Comment by smharper** [comment]
:tada: Awesome!

**Comment by samuelshaner** [comment]
The new logo looks awesome! Do you have a vector version of the logo you could add to the repo?

**Comment by nelsonag** [comment]
I second that, this is pretty nice!

**Comment by bhermanmit** [comment]
very cool!

**Comment by wbinventor** [comment]
@bhermanmit is alive!

**Pull request merged**
