### PR TITLE
Assign ZAID for metastable nuclides correctly

### PR DESCRIPTION
**Pull request by paulromano**
This pull request fixes a bug whereby the ZAID for metastable nuclides is not assigned correctly. In `ace.F90`, we currently use NXS(2) to assign the ZAID. However, this doesn't necessarily match the ID of the table itself, e.g. the table might be 95642.71c but NXS(2) gives 95242. The reason this is a problem is because we use the table ID to when looking up what stride to use for the new probability table sampling algorithm (based on `nuc_zaid_dict`). Thus, in the case of Am-242m, the key 95242 won't actually be in the dictionary and so the value returned is just garbage (some large negative value).

The actual bug fix is a one-line change in ace.F90. I've also fixed a Python 3.5-related bug in run_tests.py having to do with modifying a dictionary while iterating over it.

Any tests containing Am-242m had results that changed.

@walshjon @smharper This change probably makes more sense to you guys, so I'd appreciate if one of you can review.

### CODE REVIEW

**Comment by nelsonag** [comment]
Looks reasonable to me.  The only question that comes to mind is: Is this an idiosyncrasy with a particular data set (NNDC), and are there other idiosyncrasies that this would expose in the other data sets (Serpent, MCNP - probably not)?

**Comment by paulromano** [comment]
Each different library seems to have a different convention for metastable nuclides (the new ACE header format addresses this), so it's hard to know what NXS(2) will end up being. By relying on our own cross_sections.xml listings like I did in this PR, we should be able to avoid potential issues.

**Comment by nelsonag** [comment]
Makes sense.  It's been so long since we worked on our cross_sections.xml file generation script that I forgot we already went through the process of handling it on that end!

**Comment by nelsonag** [comment]
Looks good to me, thanks @paulromano !

**Pull request merged**
