### PR TITLE
High resolution and vector graphic OpenMC logo

### PR DESCRIPTION
**Pull request by samuelshaner**
The OpenMC logo located at `docs/source/_images/openmc.png` is fairly low resolution and looks pixelated when placed in presentations. This PR updates the OpenMC logo with new high resolution and vectorized versions. The font was hard to match, so the new logo looks slightly different. This PR includes a low resolution png for the website, a high resolution png for presentations, and a vectorized version (adobe illustrator format) for those wanting the logo to look sharp in presentations and posters. The vectorized version is editable so it can be easily edited in the future with version numbers/code variants/etc.

**Old logo**
openmc-4

**Proposed new logo**
openmc

### CODE REVIEW

**Comment by paulromano** [comment]
I do have the [OpenMC logo in SVG format](https://www.dropbox.com/s/dc7x82u9cue3a9t/OpenMC.svg?dl=0). I'm actually not crazy about our logo; we've talked about having a real graphic designer make a better logo similar to what @wbinventor did for OpenMOC.

**Comment by wbinventor** [comment]
Haha, yeah I think a new flashier logo might be a good idea. The first
question I got at my ANS talk the other day questioned why there was a
(supposed) discrepancy between the two logos which were side-by-side on my
final slide. I honestly don't think the current logo is all that bad, but
probably wouldn't want to wear a hoodie with it on it ;-)

**Comment by samuelshaner** [comment]
I agree a flashier logo would look nice for OpenMC (and also for CRPG). If nothing else, it would be nice to have a logo in the repo that doesn't look pixelated in presentations. @paulromano - the link you provided is to a uml diagram for OpenMC. Could you share a link for the svg of the logo?

**Comment by paulromano** [comment]
@samuelshaner Sorry about that - linked is fixed now!

**Comment by samuelshaner** [comment]
Thanks @paulromano, although the linked file looks to be a different version of the OpenMC logo.

**Comment by paulromano** [comment]
It is the same version -- the dropbox preview doesn't render it correctly so perhaps that's why it looks different for you? Did you actually download and open it?

**Comment by cjosey** [comment]
I propose this logo:
woo
(I'm sorry, I had to.)

**Comment by samuelshaner** [comment]
I downloaded the file and tried to open it in Adobe Illustrator but got an error saying "the operation cannot complete because of an unknown error". I opened it in safari, firefox, and ToyViewer (a basic image viewer) and the logo looks similar to the rendering on dropbox, except the full logo is shown. Does it look like the standard logo on your computer?

**Comment by paulromano** [comment]
It does look like the standard logo on my computer. Probably a font issue if I had to guess. I believe I created it in Inkscape so that would probably be your best bet.

**Comment by wbinventor** [comment]
Case in point why we overlooked you Colin in our search for a VP of
marketing for CRPG.

**Comment by samuelshaner** [comment]
It was indeed a font issue. I downloaded the [Sawasdee font](http://osp.kitchen/live/fbsp-dinner/tree/master/Sawasdee.ttf) and it looks like the standard logo in illustrator and inkscape. I'm guessing others would have a font issue if they tried to place the svg in their documents. That said, it might be nice to have a vector or high resolution raster version of the logo in the repo at some point.

**Comment by wbinventor** [comment]
I agree that including a high-quality logo as part of the repo would be nice, so that folks can include it in their presentations related to the code.

**Comment by nelsonag** [comment]
Wait... did I hear something about OpenMC hoodies?

**Pull request closed without merging**
