### PR TITLE
Changing parentheses into square brackets for creating materials_file

### PR DESCRIPTION
**Pull request by johnnyliu27**
I found this bracket issue when testing with simple problem models. Using parentheses, the input in python api will become non-iterable if there is only one material. So I think using a list will be more general.

### CODE REVIEW

**Comment by johnnyliu27** [comment]
Just found more such places in other example notebooks. I'll push another commit soon.

**Comment by paulromano** [comment]
In Python, to create a one-element tuple, you can write `(item,)`, so the call to the Materials constructor would be:
```Python
mats = openmc.Materials((fuel,))
```
Nevertheless, the change is fine so I'll go ahead and merge it.

**Comment by johnnyliu27** [comment]
Thanks for that! And I also found square brackets are used in the API documentation of [openmc.Materials](http://openmc.readthedocs.io/en/latest/pythonapi/generated/openmc.Materials.html#openmc.Materials), so might be more consistent.

But why does the CI build fail?

**Comment by paulromano** [comment]
Oh, the CI build probably failed because I merged the PR before it was done checking. Not to worry!

**Comment by johnnyliu27** [comment]
Thanks!

**Pull request merged**
